num = int(input("Digite um número: "))
print("-" * 10)
print(f"1 X {num} = {num*1}")
print(f"2 X {num} = {num*2}")
print(f"3 X {num} = {num*3}")
print(f"4 X {num} = {num*4}")
print(f"5 X {num} = {num*5}")
print(f"6 X {num} = {num*6}")
print(f"7 X {num} = {num*7}")
print(f"8 X {num} = {num*8}")
print(f"9 X {num} = {num*9}")
print(f"10 X {num} = {num*10}")
print("-" * 10)